package util;

/**
 * Class with paths e constants to system.
 * 
 * @author Samuel Santos
 */
public class Settings {
    
    /*Directory local user*/
    public static final String USER_DIR = System.getProperty("user.dir");
    
    public static final String NEWLINE =  System.getProperty("line.separator");
    
    /*File Separator '\' or '/' */
    public static final String SEPARATOR = System.getProperty("file.separator");
    
    public static final String WORKSPACE = USER_DIR + SEPARATOR + "workspace";
    
    public static final String PRIORJ_PROJECT = USER_DIR + SEPARATOR + "PriorJProjects";
    
    public static final String REPORT = USER_DIR + SEPARATOR + "report";
    
    public static final String SUITES =  REPORT+ SEPARATOR +"suites";
    
    public static final String ORDER = REPORT+ SEPARATOR + "order"; 
   
    public static final String TEMPORARY = USER_DIR + SEPARATOR + "priorjtmp";
    
    public static final String BACKUP = TEMPORARY + SEPARATOR + "backup";
    
    /*File generated by Junit with the Execution Report*/
    public static final String TEST_SUITE_XML_FILE =  "TESTS-TestSuites.xml";
 
    public static final String FILE_COVERAGE_REPORT = "coverageReport.txt";
    
    public static final String EXTERNAL = USER_DIR + SEPARATOR +"external";
    
    public static final String ASPECT_FILE = EXTERNAL + SEPARATOR + "aspectfiles";
    
    public static final String APP = USER_DIR + SEPARATOR + "resources" + SEPARATOR + "app";
    
    public static final String APP_CODE = APP + SEPARATOR + "src";
    
    public static final String APP_LIB = APP + SEPARATOR + "lib";
    
    public static final String APP_TEST = APP + SEPARATOR + "test" + SEPARATOR + "calctest";
}
